version: '26.0.0'

services:

  db:
    image: postgres:16.3-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cooking_core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postDB
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      COOKING_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
      COOKING_CORE_SETTING_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql-data:
    driver: local
